services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    networks:
      - my-network
    environment:
      MONGO_URI: mongodb://app:password@mongoDB:27017/app?authSource=admin
  
  mongoDB:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_PASSWORD: password
      MONGODB_ROOT_USER: app
      MONGODB_ENABLE_DIRECTORY_PER_DB: false
    volumes:
      - mongoDB_data:/bitnami/mongodb
    networks:
      - my-network


volumes:
  mongoDB_data:

networks:
  my-network: